name: github_repo_browser_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  flutter_riverpod: ^2.5.0 # Managed State (like ViewModel + Flow)
  freezed_annotation: ^2.4.1 # Para estados imutáveis tipo sealed classes (equivalente ao seu State)
  json_annotation: ^4.9.0
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0
  freezed: ^2.4.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
